autoInstallPeers: true
allowBuilds:
  nx: true
  '@swc/core': true
  esbuild: true
  sharp: true
packages:
  - packages/*
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - sharp
catalogMode: strict
catalog:
  '@aws/nx-plugin': 1.0.0
  nx: 23.2.0
  '@nx/js': 23.2.0
  '@nx/workspace': 23.2.0
  typescript: ~6.0.3
  '@biomejs/biome': 2.5.12
  '@aws/nx-plugin-mcp': ^1.0.0
  husky: 9.1.7
